### ISSUE TITLE
please select MIT license in github

### ISSUE THREAD

**Issue by Neovariance** [Supert/shibari#2]
so it appear in the header after contributor like here for example
https://github.com/yasirkula/UnityRuntimeInspector

**Comment by Supert** [comment]
Good catch, Neovariance!

It seems like GitHub haven't processed license file in a first time.

In fact, I've just removed my LICENSE.md file, and then precisely followed [this article](https://help.github.com/articles/adding-a-license-to-a-repository/) with no luck (you could notice the mess in the last commits).

I've contacted GitHub support. Hope they can help.

Thank you for noticing it,
Alex.

**Comment by Supert** [comment]
LICENSE.md was conflicting with LICENSE.meta.
